Saving some progress.

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,4 +1,12 @@
 #!/bin/sh
+
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
+
 FILES=$(git diff --diff-filter=rd --cached --name-only -- . ':!*.json' ':!*.txt' ':!*.gitignore' ':!pre-commit' | sed 's| |\\ |g')
 [ -z "$FILES" ] && exit 0
 
